name: Build and Publish React Website

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build Project
        run: |
          npm install
          npm run build --if-present

      - name: List output files
        run: ls

      - name: FTP-Deploy
        uses: SamKirkland/FTP-Deploy-Action@master
        env:
          ftp-server :  ${{secrets.FTP_SERVER2}}
          ftp-username :  ${{secrets.FTP_PASSWORD}}
          ftp-password :  ${{secrets.FTP_USERNAME}}
          local-dir : build
